// src/components/summary/summary-card.tsx
/**
 * Displays Claude's AI-generated neutral summary of a completed debate.
 * Shows loading state, content, and attribution.
 */

'use client'

import { cn } from '@/lib/utils'
import { useSummaryStore } from '@/store/summary-store'

interface SummaryCardProps {
  className?: string
}

export function SummaryCard({ className }: SummaryCardProps) {
  const claudeSummary = useSummaryStore((s) => s.claudeSummary)
  const isSummaryLoading = useSummaryStore((s) => s.isSummaryLoading)

  return (
    <section className={cn('w-full', className)}>
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex items-center justify-center w-10 h-10 rounded-full bg-violet-500/10">
            <svg
              className="w-5 h-5 text-violet-600 dark:text-violet-400"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <path d="M13.827 3.52l5.313 16.96h-3.72L14.157 17H9.843l-1.263 3.48H4.86L10.173 3.52h3.654zm-.534 10.639L12 9.441l-1.293 4.718h2.586z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-foreground">Summary</h2>
        </div>
        <p className="text-muted-foreground">A neutral analysis of the debate</p>
      </div>

      <div
        className={cn(
          'rounded-xl border-2 border-violet-500/20 bg-violet-500/5 p-6',
          'transition-all duration-300'
        )}
      >
        {isSummaryLoading ? (
          <div className="space-y-4 animate-pulse">
            <div className="h-4 bg-muted rounded w-3/4" />
            <div className="h-4 bg-muted rounded w-full" />
            <div className="h-4 bg-muted rounded w-5/6" />
            <div className="h-4 bg-muted rounded w-full" />
            <div className="h-4 bg-muted rounded w-2/3" />
          </div>
        ) : claudeSummary ? (
          <div className="prose prose-neutral dark:prose-invert max-w-none">
            <div className="whitespace-pre-wrap text-foreground/90 leading-relaxed">
              {claudeSummary}
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <p className="text-muted-foreground">Summary not available for this debate.</p>
          </div>
        )}
      </div>

      {claudeSummary && (
        <div className="mt-4 flex items-center justify-end gap-2 text-sm text-muted-foreground">
          <span>Generated by</span>
          <span className="font-medium text-violet-600 dark:text-violet-400">
            Claude (Anthropic)
          </span>
        </div>
      )}
    </section>
  )
}
