// disclaimers-section.tsx
/**
 * Legal disclaimers section for AI-generated content.
 * Warns users about limitations and inappropriate reliance on debate outputs.
 */
'use client'

import { motion } from 'framer-motion'
import { AlertTriangle } from 'lucide-react'
import { useRef } from 'react'

import { useInView } from '@/hooks/use-in-view'

// Apple-style easing curve
const appleEase = [0.16, 1, 0.3, 1] as const

const doNotRelyOn = [
  'Medical diagnoses or health decisions',
  'Legal advice or interpretation',
  'Financial or investment decisions',
  'Any professional advice requiring licensed expertise',
]

// Soft fade-in variants (no movement - lower emphasis for legal)
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      duration: 0.7,
      ease: appleEase,
      staggerChildren: 0.08,
    },
  },
}

const headerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      duration: 0.6,
      ease: appleEase,
    },
  },
}

const iconVariants = {
  hidden: { opacity: 0, scale: 0.92 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      duration: 0.5,
      ease: appleEase,
    },
  },
}

const dividerVariants = {
  hidden: { opacity: 0, scaleX: 0 },
  visible: {
    opacity: 1,
    scaleX: 1,
    transition: {
      duration: 0.6,
      ease: appleEase,
      delay: 0.15,
    },
  },
}

const contentVariants = {
  hidden: { opacity: 0 },
  visible: (i: number) => ({
    opacity: 1,
    transition: {
      duration: 0.55,
      ease: appleEase,
      delay: 0.2 + i * 0.08,
    },
  }),
}

const bulletVariants = {
  hidden: { opacity: 0 },
  visible: (i: number) => ({
    opacity: 1,
    transition: {
      duration: 0.4,
      ease: appleEase,
      delay: 0.35 + i * 0.05,
    },
  }),
}

export function DisclaimersSection() {
  const sectionRef = useRef<HTMLElement>(null)
  const isInView = useInView(sectionRef, { threshold: 0.1, once: true })

  return (
    <section ref={sectionRef} id="disclaimers" className="scroll-mt-20 py-6 md:py-8">
      {/* Narrow max-width legal panel */}
      <motion.div
        className="mx-auto max-w-2xl"
        variants={containerVariants}
        initial="hidden"
        animate={isInView ? 'visible' : 'hidden'}
      >
        {/* Header with icon - centered */}
        <motion.div className="flex flex-col items-center text-center" variants={headerVariants}>
          <motion.div
            className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10 ring-1 ring-amber-500/20"
            variants={iconVariants}
          >
            <AlertTriangle className="h-6 w-6 text-amber-500" aria-hidden="true" />
          </motion.div>
          <p className="text-sm font-medium uppercase tracking-widest text-primary/80">Legal</p>
          <h2 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
            Important Disclaimers
          </h2>
        </motion.div>

        {/* Divider */}
        <motion.div
          className="my-6 h-px"
          variants={dividerVariants}
          style={{
            background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent)',
          }}
        />

        {/* Content with lower opacity text */}
        <div className="space-y-5">
          <motion.p
            className="text-base leading-relaxed text-foreground/70"
            variants={contentVariants}
            custom={0}
          >
            <strong className="text-foreground/90">
              All debate content is generated by AI models
            </strong>{' '}
            and should not be treated as factual or authoritative. Large language models can produce
            incorrect, biased, or misleading statements — even when they sound confident.
          </motion.p>

          <div
            className="h-px"
            style={{
              background: 'linear-gradient(90deg, rgba(255,255,255,0.06), transparent 80%)',
            }}
          />

          <motion.p
            className="text-base leading-relaxed text-foreground/70"
            variants={contentVariants}
            custom={1}
          >
            The &quot;winner&quot; of a debate is not an objective truth. It is one AI&apos;s
            assessment of argumentation quality based on predefined criteria. Reasonable people (and
            AIs) may disagree.
          </motion.p>

          <div
            className="h-px"
            style={{
              background: 'linear-gradient(90deg, rgba(255,255,255,0.06), transparent 80%)',
            }}
          />

          <motion.div variants={contentVariants} custom={2}>
            <p className="text-base leading-relaxed text-foreground/70">
              <strong className="text-foreground/90">
                Debate Lab is for entertainment and educational purposes.
              </strong>{' '}
              Do not rely on AI-generated content for:
            </p>
            <ul className="mt-4 space-y-2 pl-4">
              {doNotRelyOn.map((item, index) => (
                <motion.li
                  key={index}
                  className="flex items-center gap-3 text-sm text-foreground/60"
                  variants={bulletVariants}
                  custom={index}
                  initial="hidden"
                  animate={isInView ? 'visible' : 'hidden'}
                >
                  <span className="h-1 w-1 rounded-full bg-amber-500/60" />
                  {item}
                </motion.li>
              ))}
            </ul>
          </motion.div>

          <div
            className="h-px"
            style={{
              background: 'linear-gradient(90deg, rgba(255,255,255,0.06), transparent 80%)',
            }}
          />

          <motion.p
            className="text-sm leading-relaxed text-foreground/50"
            variants={contentVariants}
            custom={3}
          >
            When in doubt, consult qualified professionals. AI debates can introduce you to
            different perspectives, but they should not replace expert guidance.
          </motion.p>
        </div>
      </motion.div>
    </section>
  )
}
