// src/components/features/disclaimers-section.tsx
import { Prose } from '@/components/ui/prose'

export function DisclaimersSection() {
  return (
    <section id="disclaimers" className="scroll-mt-20">
      <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
        Important Disclaimers
      </h2>
      <Prose className="mt-6">
        <p>
          <strong>All debate content is generated by AI models</strong> and should not be treated as
          factual or authoritative. Large language models can produce incorrect, biased, or
          misleading statements — even when they sound confident.
        </p>
        <p>
          The &quot;winner&quot; of a debate is not an objective truth. It is one AI&apos;s
          assessment of argumentation quality based on predefined criteria. Reasonable people (and
          AIs) may disagree.
        </p>
        <p>
          <strong>LLM Debate Arena is for entertainment and educational purposes.</strong> Do not
          rely on AI-generated content for:
        </p>
        <ul>
          <li>Medical diagnoses or health decisions</li>
          <li>Legal advice or interpretation</li>
          <li>Financial or investment decisions</li>
          <li>Any professional advice requiring licensed expertise</li>
        </ul>
        <p>
          When in doubt, consult qualified professionals. AI debates can introduce you to different
          perspectives, but they should not replace expert guidance.
        </p>
      </Prose>
    </section>
  )
}
